// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqSEcy7D19eAATjolErCHRBprxTTqxhg',
    appId: '1:213811827453:web:5cc410708fef953140e494',
    messagingSenderId: '213811827453',
    projectId: 'wordling-d49b8',
    authDomain: 'wordling-d49b8.firebaseapp.com',
    storageBucket: 'wordling-d49b8.appspot.com',
    measurementId: 'G-S73TKG4E17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXpz2wZPU0aIevR-NTkkYhwUPLjCo6zKU',
    appId: '1:213811827453:android:5bfda53b7833d88140e494',
    messagingSenderId: '213811827453',
    projectId: 'wordling-d49b8',
    storageBucket: 'wordling-d49b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtnaKtfXO1x8c8mM3Qqun5MTcxCOgRtZo',
    appId: '1:213811827453:ios:b67ad7d69a3dab0240e494',
    messagingSenderId: '213811827453',
    projectId: 'wordling-d49b8',
    storageBucket: 'wordling-d49b8.appspot.com',
    iosClientId: '213811827453-6fa18e704o33jpviek1a6irnibv0nos2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtnaKtfXO1x8c8mM3Qqun5MTcxCOgRtZo',
    appId: '1:213811827453:ios:b55fbbc11485ba6940e494',
    messagingSenderId: '213811827453',
    projectId: 'wordling-d49b8',
    storageBucket: 'wordling-d49b8.appspot.com',
    iosClientId: '213811827453-3mtu9o3s621fsgdoj6m51oei075daian.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordling.RunnerTests',
  );
}
